### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by TssT16** [MaverickMartyn/youtube-music-desktop#7]
Hi,
my versions
Archlinux OS
`yarn -v 1.16.0`
`node -v v11.13.0`
`electron -v v3.1.6`
after `yarn run dist` I get error
"yarn run v1.16.0
$ build
/bin/sh: build: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."

Has you an ideer what I need to install to have the build command?

**Comment by timofeysie** [comment]
I'm having the same issue with a project setup from [this article](https://www.codementor.io/randyfindley/how-to-build-an-electron-app-using-create-react-app-and-electron-builder-ss1k0sfer).  Just thought I would add my details in case it helps.
```
$ yarn electron-pack
yarn run v1.13.0
$ yarn build
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  36.44 KB  build/static/js/2.b41502e9.chunk.js
  763 B     build/static/js/runtime~main.d653cc00.js
  601 B     build/static/js/main.643ebfc4.chunk.js
  517 B     build/static/css/main.2cce8147.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://bit.ly/CRA-deploy

$ build -mw
/bin/sh: build: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MaverickMartyn** [comment]
@TssT16 and @timofeysie where did you guys get the idea of running the `build -mw` command?
Did you follow the instructions in the `README.md` file?

**Comment by TssT16** [comment]
I just run **yarn run dist** in the **youtube-music-desktop-master** folder.
Output:
```
yarn run dist
yarn run v1.17.3
$ build
/bin/sh: build: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MaverickMartyn** [comment]
Ah. Sorry. I misread the output.
I should note that I have not tested this on anything but Windows at this time.
Also, which branch are you using? I have a development branch, where I am doing the re-write.
Maybe you'll have more luck with that. It's also the only one I am currently updating.
EDIT: Found this after a quick Google Search: https://github.com/reactstrap/reactstrap/issues/711
Try running `yarn install` first. I should probably add that to the docs, since it may not be a given.
If that doesn't work look through the linked issue, and see if they have other ideas.

**Comment by TssT16** [comment]
thanks man
